### ISSUE TITLE
[Feature request] place down the ores

### ISSUE THREAD

**Issue by ChillPenguinVR** [Spalding004/fortunate_1_15#4]
Could there be a way to place the chunks back down? Some of the mods like Astral sorcery require the ores themselves. In astral sorcery's case, to get starmetal you have to place iron ore near a starlight collector crystal for it to be transformed into starmetal ore. As I have this mod in my game, I am unable to get the starmetal ore without cheating because i cannot place iron ore down around it.

**Comment by Spalding004** [comment]
You will need to use silk touch to collect them.
